### ISSUE TITLE
another dns server

### ISSUE THREAD

**Issue by andricik** [retupmoca/P6-Net-DNS#14]
When in 

`my $resolver = Net::DNS.new('8.8.8.8');`

I use another server instead of 8.8.8.8, lookup fails like this:

Type check failed in assignment to @!name; expected Str but got Any (Any)
in method new at /home/andricik/.rakudobrew/moar-nom/install/share/perl6/site/sources/0744EDC800DA8C9888E037A4C19403B29C9281C1 (Net::DNS::Message::Resource) line 41
 in method new at /home/andricik/.rakudobrew/moar-nom/install/share/perl6/site/sources/D5AF31DC5E4214A6436C623F082345A3939373E8 (Net::DNS::Message) line 47
 in method lookup at /home/andricik/.rakudobrew/moar-nom/install/share/perl6/site/sources/6330B73A0255420895A99758C9F645802520DA06 (Net::DNS) line 74
 in block <unit> at test line 7

My test script:
```
use v6;
use Net::DNS;
my $resolver = Net::DNS.new('10.0.1.1');
my @addresses = $resolver.lookup('A', 'google.com');
my $ip = @addresses[0];
say $ip.perl;
```
10.0.1.1 is working DNS server running BIND9 on local network. I checked several other (private or public IP) without success.
Am I missing something or does the module work only with google resolver?

Thanks, Marek.

**Comment by retupmoca** [comment]
I just fixed a bug with similar symptoms - can you re-test and see if it resolved your issue?
