### ISSUE TITLE
How do I know what error occurred?

### ISSUE THREAD

**Issue by davehayes** [retupmoca/P6-Net-DNS#21]
```
use Net::DNS;
my $dns = Net::DNS.new('8.8.8.8');
my $lookup = $dns.lookup('A', 'mqkjqwew.rrr');
dd $lookup;
```

prints

```
Seq $lookup = $(().Seq)
```

There's apparently no indication of error here (e.g. REFUSED, SERVFAIL). How would I get this error?

**Comment by rbt** [comment]
On RCODE != 0, you now get an X::Net::DNS object (via fail) which has a shortcut for getting rcode-name and rcode-value.
