### ISSUE TITLE
A nice start

### ISSUE THREAD

**Issue by kjpye** [retupmoca/P6-Net-DNS#3]
As somebody who makes some interesting use of the perl5 Net::DNS module (to the extent that I needed to modify it) I looked with interest at your start on a perl6 module.

It looks good at first glance, but some minor enhancements would make it much more useful...

1. It makes the assumption that the result of a lookup is a single record. This is often incorrect, and almost always for some record types (NS for example). There needs to be a way of getting all results for a query. Perhaps the result could still stringify to the firsdt value returned.

2. Following on from that the results of some queries (the unimplemented zone transfers for example) contain long lists of records of varying types, I'll be interested to see how you handle that.

3. You're only using TCP rather than the purer UDP (with fallback to TCP for long answers). This makes the code a lot simpler, and should work everywhere, except where the firewall administrators don't know what they're doing.

4. Being able to handle SOA queries would be a nice enhancement in the short term, perhaps leading to AXFR and IXFR queries later.

**Comment by retupmoca** [comment]
I've opened #12 to track the IXFR feature.
