### ISSUE TITLE
None of the parametric role variants for 'Buf' matched the arguments supplied.

### ISSUE THREAD

**Issue by bbkr** [retupmoca/P6-Net-DNS#8]
Following error randomly occurs when resolving is done on Promises:

```
$ perl6 -e 'use Net::DNS; await do for "gmail.com", "yahoo.com", "hotmail.com" -> $domain { start { Net::DNS.new( "192.168.1.1" ).lookup( "MX", $domain ) } };'

Unhandled exception: None of the parametric role variants for 'Buf' matched the arguments supplied.
Ambiguous call to ''; these signatures all match:
:(Mu ::$?CLASS ::::?CLASS, ::T $ = { ... })
:(Mu ::$?CLASS ::::?CLASS, ::T $ = { ... })
  in throw (gen/jvm/CORE.setting:11920)
  in result (gen/jvm/CORE.setting:19257)
  in await (gen/jvm/CORE.setting:20778)
  in await (gen/jvm/CORE.setting:20777)
  in  (gen/jvm/CORE.setting:8108)
  in reify (gen/jvm/CORE.setting:8031)
  in  (gen/jvm/CORE.setting:7944)
  in reify (gen/jvm/CORE.setting:7915)
  in gimme (gen/jvm/CORE.setting:8431)
  in sink (gen/jvm/CORE.setting:8908)
  in MAIN (gen/jvm/main.nqp:41)
  in <mainline> (gen/jvm/main.nqp:35)
  in  (gen/jvm/main.nqp)
```

System info - OS X 10.10 Yosemite:

```
$ perl6 --version
This is perl6 version 2014.09 built on JVM

$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

$ uname -a
Darwin bbkr.org 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
```

**Comment by retupmoca** [comment]
I've managed to golf this down to 'await do for 1..5 { start { buf8.new } }', which looks like a rakudo bug. I have a possible fix in mind, but need to get someone smarter than me to help review.

**Comment by retupmoca** [comment]
This buf8 golf now runs correctly, but I still am getting errors for your original test code, including:

- This representation (Null) does not support elems
- MVMArray: Can't shift from an empty array
- Cannot .shift from an empty Array
- Crash without any message
- as well as a few others

Given the type of errors (and the lack of globals in Net::DNS), I'm assuming there are more rakudo bugs to find, although I may try more golfing when I get time.

**Comment by retupmoca** [comment]
With a perl6 built yesterday: I'm not seeing any error messages, but I now get one of three failure modes: no return value, a crash with no message, or the correct result.

**Comment by retupmoca** [comment]
With latest rakudo, this now seems to work properly!
